version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: eli_postgres
    environment:
      POSTGRES_DB: eli_test_strips
      POSTGRES_USER: eli_user
      POSTGRES_PASSWORD: eli_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  backend:
    build: ./backend
    container_name: eli_backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://eli_user:eli_password@postgres:5432/eli_test_strips
      NODE_ENV: development
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
    depends_on:
      - postgres

volumes:
  postgres_data:
